### ISSUE TITLE
New content-driven home page

### ISSUE THREAD

**Issue by seancdavis** [seancdavis/seancdavis-com#166]
The original design included the ability to list posts on the home page. I don't need to follow it exactly, but would like to see posts and videos on the home page. (That means this is likely blocked by #165.)

What I haven't really thought through yet is:

- Should home page items be featured? Should it be a running stream of the latest content? Some combination of both?
- How do I (or _should_ I) include content pieces published elsewhere.

The benefit of having _some_ external content on the home page is that I could build up a list of everything I've published elsewhere. That could be beneficial, should I choose to pull it in at some point.

**Comment by seancdavis** [comment]
Changes to the home page will include:

- [ ] Remove bio (some of it moves to about in #201)
- [ ] Add support for videos as a collection and a specific blog-like template (#165)
- [ ] Add external content as data that doesn't get rendered, just for posterity for now. (#202)
- [ ] Add a list of new and featured content. Featured on top, newest below. (this issue)

**Comment by seancdavis** [comment]
Thought about this some more today. Here's the content that I would like to include, in rough order:

- Hero section — _Build better websites_
- Featured content
- Live streams — Good Websites Live + Sandwich Time
- Featured on — Podcasts and other shows I've been on. Might even want to include talks here, too.
- The Spinneret CTA, perhaps with a link to the last 2-3 issues? Does this also mean the footer CTA should be removed? Or maybe this is up high enough in the page that it feels detached. Another option would be to put a form in or near the hero section and treat it as updates.
- Latest articles and videos? It would be nice that this would be rotating content to keep the page fresh. Wonder if it should be up higher?

I plan to play with these as individual sections and see how they fit together. Thinking of a mashup of blog, personal site, and startup.
