### ISSUE TITLE
Introduce Developer Toolbelt/Toolkit

### ISSUE THREAD

**Issue by seancdavis** [seancdavis/seancdavis-com#367]
## Tasks

**Tools**

- [x] New content type `Tool` (route: `/tools/[slug]`) with structured data. (See below for initial thoughts.)
- [x] Tool detail page that lists structured data, along with my hot take(s).
- [x] Include CTA for a reader to update a value that is out of date. Note that #441 is potentially coming soon.
- [x] Add meta image generator.
- [x] Because meta image generator will use the logo, if it exists, it would be great to handle automatically uploading the logo, too. That way I can edit exclusively in codespaces.
- ~#447~ UPDATE: Not going to do this as this part of the work. I want to see how it plays out first.
- [x] Feed with distinct card style. This should be organized alphabetically, and (for now) list all tools. No pagination.
- [ ] Add logo to cards. (Need SVG transformations with Imgix source first.)
- [x] Clean up syntax highlighting on these views. Something that can be reused elsewhere as necessary.

**Lists**

- [ ] New content type `Toolkit` (route: `/toolkits/[slug]`) that lists individual tools in the kit, with comments for each as necessary.
- [ ] Toolkit detail page that renders the structured data and links to the tools.
- [ ] Add meta image generator.
- ~CTA to ask for a new toolkit?~ Going to wait to see what comes of #447 and related before working anything like this.
- [ ] There should be a feed of individual lists with a distinct card style. It is organized by filename date and paginated.
- [ ] Surface last updated date on tools

**Landing Page**

- [ ] Landing page of all tools and toolkits (route: `/developer-toolkit`). (See below for initial exploration.)

**Feeds**

- [ ] Toolkits should be added to the blog, but not individual tools. Individual tools do not have a date associated with them.
- [ ] Add toolkits (and tools?) to the home page in some way.
- [ ] Consider addressing #370 as part of this work. Otherwise, tools are going to automatically show up in the topic feeds, and it might look a little awkward.
- [ ] Toolkits should be present on the XML feeds, but not individual tools.

### Tool Schema

This is the beginning of what I'd like to capture about a tool, in addition to the page basics:

```yaml
open_source: true/false
free_plan: true/false
sources:
  website: "..."
  github: "..."
  npm: "..."
```

Keep dates in the filename to serve as "created" dates. But also add a `last_updated` property to know when the information changed. In general, the feeds of these tools should be by: topic, kit, and alphabetically. The filename date will only be used when sourcing new tools added for the newsletter.

Thinking I'm also going to want a workflow in which I can add a logo locally and have it become part of the page and the meta image. When I work, the structure would look like this:

```yaml
---
tmp_logo:
  ratio: 1.5 # width / length
  src: /static/my-logo.svg
---
```

And after processing, it looks like this:

```yaml
---
logo: /images/tools/[tool]/[tool]-logo.svg
---
```

### Toolkit Schema

Just so this is easily accessible, may want to consider adding the `Post` tag automatically here.

Otherwise, aside from the typical page attributes, we'll want a `tools` property, which would contain:

- `ref`: The name of the tool file.
- `comments`: Comments within the context of the kit, relating to this file.

To make the intro/outro easier, I may want to consider a component or direct include, so that I don't have to have intro/outro fields in the frontmatter. But instead could do something like this:

```liquid
Intro goes here ...

{% tool_list tools=tools %}

Outro goes here ...
```

### Landing Page

This doesn't have to be anything fancy right away. I'm thinking of a few sections:

- Popular kits - link to explore all kits
- Recently-discovered tools (created date comes in here) - link to all tools
- [TBD] Would be cool to list all topics used by tools, and then to link to `/topics/[topic]/tools` with a list of those tools. I need to move in this sort of direction for #370, but not sure this is the right time.

**Comment by seancdavis** [comment]
UPDATE: After much deliberation, I've decided not to pursue these new content types.
